<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        $company = Company::first();

        if (! $company) {
            $this->command->error('No company found. Please run CompanySeeder first.');

            return;
        }

        $roles = [
            'Owner' => [
                'description' => 'Full system access - business owner',
                'permissions' => Permission::all()->pluck('code')->toArray(),
            ],
            'Administrator' => [
                'description' => 'System administrator with full access except company settings',
                'permissions' => Permission::whereNotIn('code', [
                    'companies.delete',
                    'companies.update',
                ])->pluck('code')->toArray(),
            ],
            'Branch Manager' => [
                'description' => 'Manages a specific branch',
                'permissions' => [
                    'dashboard.view',
                    'branches.view',
                    'warehouses.view',
                    'products.view',
                    'categories.view',
                    'brands.view',
                    'units.view',
                    'stock.view',
                    'stock_movements.view',
                    'pos.access',
                    'pos.hold_order',
                    'pos.resume_order',
                    'sales_orders.view',
                    'sales_orders.create',
                    'sales_orders.update',
                    'quotations.view',
                    'quotations.create',
                    'quotations.update',
                    'invoices.view',
                    'invoices.create',
                    'invoices.print',
                    'sales_returns.view',
                    'sales_returns.create',
                    'refunds.view',
                    'purchase_orders.view',
                    'purchase_orders.create',
                    'purchase_receipts.view',
                    'purchase_receipts.create',
                    'suppliers.view',
                    'customers.view',
                    'customers.create',
                    'customers.update',
                    'payments.view',
                    'payments.create',
                    'cash_sessions.view',
                    'cash_sessions.open',
                    'cash_sessions.close',
                    'cash_sessions.reconcile',
                    'bank_accounts.view',
                    'bank_transactions.view',
                    'expenses.view',
                    'expenses.create',
                    'employees.view',
                    'attendance.view',
                    'shifts.view',
                    'shifts.create',
                    'commissions.view',
                    'promotions.view',
                    'coupons.view',
                    'reports.sales',
                    'reports.profit',
                    'reports.inventory',
                    'reports.purchases',
                    'reports.expenses',
                    'reports.customers',
                    'reports.branches',
                    'reports.cash',
                ],
            ],
            'Sales Manager' => [
                'description' => 'Manages sales operations',
                'permissions' => [
                    'dashboard.view',
                    'products.view',
                    'categories.view',
                    'brands.view',
                    'units.view',
                    'stock.view',
                    'pos.access',
                    'pos.hold_order',
                    'pos.resume_order',
                    'pos.discount',
                    'sales_orders.view',
                    'sales_orders.create',
                    'sales_orders.update',
                    'quotations.view',
                    'quotations.create',
                    'quotations.update',
                    'quotations.convert',
                    'invoices.view',
                    'invoices.create',
                    'invoices.print',
                    'sales_returns.view',
                    'sales_returns.create',
                    'refunds.view',
                    'customers.view',
                    'customers.create',
                    'customers.update',
                    'customer_groups.view',
                    'payments.view',
                    'payments.create',
                    'promotions.view',
                    'coupons.view',
                    'reports.sales',
                    'reports.profit',
                    'reports.customers',
                ],
            ],
            'Cashier' => [
                'description' => 'Point of sale operator',
                'permissions' => [
                    'dashboard.view',
                    'products.view',
                    'stock.view',
                    'pos.access',
                    'pos.hold_order',
                    'pos.resume_order',
                    'sales_orders.view',
                    'sales_orders.create',
                    'invoices.view',
                    'invoices.create',
                    'invoices.print',
                    'customers.view',
                    'customers.create',
                    'payments.view',
                    'payments.create',
                    'cash_sessions.view',
                    'cash_sessions.open',
                    'cash_sessions.close',
                ],
            ],
            'Warehouse Manager' => [
                'description' => 'Manages warehouse operations',
                'permissions' => [
                    'dashboard.view',
                    'warehouses.view',
                    'warehouses.create',
                    'warehouses.update',
                    'products.view',
                    'categories.view',
                    'brands.view',
                    'units.view',
                    'stock.view',
                    'stock.adjust',
                    'stock.transfer',
                    'stock.count',
                    'stock_movements.view',
                    'purchase_receipts.view',
                    'purchase_receipts.create',
                    'purchase_returns.view',
                    'purchase_returns.create',
                    'reports.inventory',
                ],
            ],
            'Warehouse Staff' => [
                'description' => 'Warehouse operations staff',
                'permissions' => [
                    'dashboard.view',
                    'warehouses.view',
                    'products.view',
                    'stock.view',
                    'stock.count',
                    'stock_movements.view',
                    'purchase_receipts.view',
                    'purchase_receipts.create',
                ],
            ],
            'Purchasing Staff' => [
                'description' => 'Handles purchasing operations',
                'permissions' => [
                    'dashboard.view',
                    'products.view',
                    'categories.view',
                    'brands.view',
                    'units.view',
                    'suppliers.view',
                    'suppliers.create',
                    'suppliers.update',
                    'purchase_orders.view',
                    'purchase_orders.create',
                    'purchase_orders.update',
                    'purchase_receipts.view',
                    'purchase_receipts.create',
                    'purchase_returns.view',
                    'purchase_returns.create',
                    'payments.view',
                    'payments.create',
                    'reports.purchases',
                    'reports.suppliers',
                ],
            ],
            'Accountant' => [
                'description' => 'Handles accounting and finance',
                'permissions' => [
                    'dashboard.view',
                    'invoices.view',
                    'payments.view',
                    'cash_sessions.view',
                    'cash_sessions.reconcile',
                    'bank_accounts.view',
                    'bank_accounts.create',
                    'bank_accounts.update',
                    'bank_transactions.view',
                    'bank_transactions.create',
                    'bank_transactions.reconcile',
                    'expenses.view',
                    'expenses.create',
                    'expenses.approve',
                    'expense_categories.view',
                    'expense_categories.create',
                    'expense_categories.update',
                    'accounting.accounts.view',
                    'accounting.accounts.create',
                    'accounting.accounts.update',
                    'accounting.journal_entries.view',
                    'accounting.journal_entries.create',
                    'accounting.journal_entries.post',
                    'accounting.reports.view',
                    'reports.sales',
                    'reports.profit',
                    'reports.expenses',
                    'reports.tax',
                ],
            ],
            'HR' => [
                'description' => 'Human resources management',
                'permissions' => [
                    'dashboard.view',
                    'employees.view',
                    'employees.create',
                    'employees.update',
                    'attendance.view',
                    'attendance.manage',
                    'shifts.view',
                    'shifts.create',
                    'shifts.update',
                    'commissions.view',
                    'reports.employees',
                ],
            ],
        ];

        foreach ($roles as $name => $data) {
            $role = Role::firstOrCreate(['name' => $name, 'company_id' => $company->id], [
                'description' => $data['description'],
                'status' => 'active',
                'company_id' => $company->id,
            ]);

            $permissions = Permission::whereIn('code', $data['permissions'])->get();
            $role->permissions()->sync($permissions);
        }
    }
}
